### ISSUE TITLE
Bug with Django 3.2: get_meta() missing 1 required positional argument: 'is_partition'

### ISSUE THREAD

**Issue by mpibpc-mroose** [farhan0581/django-inspectdb-refactor#10]
When running and import I get the following stacktrace:

```
inspectdb_refactor --database=arpguard --app=API
"C:\Program Files\JetBrains\PyCharm 2019.2\bin\runnerw64.exe" D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm 2019.2\plugins\python\helpers\pycharm\django_manage.py" inspectdb_refactor --database=arpguard --app=API D:/Local_Development/DeviceAndNetworkInventory/ArpGuardAPI/source
Tracking file by folder pattern:  migrations
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\plugins\python\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\plugins\python\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:/Local_Development/DeviceAndNetworkInventory/ArpGuardAPI/source\manage.py", line 22, in <module>
    main()
  File "D:/Local_Development/DeviceAndNetworkInventory/ArpGuardAPI/source\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\inspectdb_refactor\management\commands\inspectdb_refactor.py", line 118, in handle
    self.handle_inspection(options)
  File "D:\Local_Development\DeviceAndNetworkInventory\venv-arpguard-api\lib\site-packages\inspectdb_refactor\management\commands\inspectdb_refactor.py", line 270, in handle_inspection
    for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view):
TypeError: get_meta() missing 1 required positional argument: 'is_partition'

```
For me this seems to be an incompatibility with newer Django versions. I'm using Django 3.2 for my project. The last working version seems to be 2.1.

**Comment by madzul** [comment]
Last time I got the same problem [Issue #9](https://github.com/farhan0581/django-inspectdb-refactor/issues/9)
Try using the github's version, not the one from PyPi:
`pip install -e git+https://github.com/farhan0581/django-inspectdb-refactor.git#egg=django_inspectdb_refactor`
