### ISSUE TITLE
TypeError: get_meta() missing 1 required positional argument: 'is_view'

### ISSUE THREAD

**Issue by hickeroar** [farhan0581/django-inspectdb-refactor#5]
Django 2.1.5

Exact command I'm running:

`python3 manage.py inspectdb_refactor --database=default --app=api`

Full stack trace:

```Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/inspectdb_refactor/management/commands/inspectdb_refactor.py", line 118, in handle
    self.handle_inspection(options)
  File "/usr/local/lib/python3.6/dist-packages/inspectdb_refactor/management/commands/inspectdb_refactor.py", line 265, in handle_inspection
    for meta_line in self.get_meta(table_name, constraints, column_to_field_name):
TypeError: get_meta() missing 1 required positional argument: 'is_view'```

**Comment by farhan0581** [comment]
The issue has been resolved.Please use the latest version 0.4

**Comment by mehdiselbi** [comment]
same issue with Django 2.2.2 and Django_inspectdb_refractor 0.4, any new update or solution to this issue?

**Comment by ronniebrito** [comment]
as an straightforward solution , changed inspectdb_refactor.py to 

 `   for meta_line in self.get_meta(table_name, constraints, column_to_field_name, is_view, is_partition=0):`
